name: Continuous integration

on:
  push:
    branches:
      - master
    tags:
      - release-*
    paths-ignore:
      - "site/**/*"
      - schemas/**/*
      - util/**/*
  workflow_dispatch: {}
  pull_request:
    branches:
      - master

jobs:
  auto_tag:
    name: Tag Releases
    if: (github.event_name == 'push' && github.ref_type == 'branch') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          token: ${{ secrets.WORKFLOW_PAT }}
          fetch-depth: 0
      - uses: tamasfe/auto-tag@f7f507df92bd992ad07a73c68614ac1909739e24 # v5
        with:
          name: tamasfe
          email: me@tamasfe.dev
          token: ${{ secrets.WORKFLOW_PAT }}

  fmt:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: docker://docker.io/tamasfe/taplo:latest
        with:
          args: fmt --check --diff

  test:
    name: Test on Rust stable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Install latest Rust toolchain
        run: rustup update --no-self-update
      - uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2.8.2
      - name: Test Taplo
        run: cargo test -p taplo
      - name: Check formatting regression
        run: cargo run -- fmt --check
      - name: Check if git index is clean
        run: git diff-index --quiet HEAD --

  check_wasm32:
    name: Check on WASM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Install latest Rust toolchain
        run: |
          rustup update --no-self-update
          rustup target add wasm32-unknown-unknown
      - uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2.8.2
      - name: Check WASM crates (locked)
        run: cargo check -p taplo-wasm -p pipelex-wasm --target wasm32-unknown-unknown --locked

  toml_test:
    name: Run toml-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Install latest Rust toolchain
        run: |
          rustup update --no-self-update
      - uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2.8.2
      - name: Retrieve toml-test
        run: |
          wget https://github.com/BurntSushi/toml-test/releases/download/v1.1.0/toml-test-v1.1.0-linux-amd64.gz
          gunzip toml-test-v1.1.0-linux-amd64.gz
          chmod +x toml-test-v1.1.0-linux-amd64
      - name: Build taplo-cli
        run: |
          cargo build --bin taplo --no-default-features --features "rustls-tls,toml-test"
      - name: Run toml-test
        run: ./toml-test-v1.1.0-linux-amd64 ./target/debug/taplo -- toml-test

  test-msrv-lib:
    name: Test libraries with MSRV
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Install latest Rust toolchain
        run: |
          rustup update --no-self-update
          rustup default 1.74
      - uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2.8.2
      - name: Test MSRV for taplo
        run: |
          cargo check -p lsp-async-stub -p taplo-common -p taplo-lsp -p taplo
          cargo test  -p lsp-async-stub -p taplo-common -p taplo-lsp -p taplo

  test-msrv-bin:
    name: Test binaries with MSRV
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Install latest Rust toolchain
        run: |
          rustup update --no-self-update
          rustup default 1.74
      - uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2.8.2
      - name: Test taplo-cli
        run: |
          cargo check -p taplo-cli
          cargo test  -p taplo-cli

  test-msrv-wasm:
    name: Test WASM with MSRV
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Install latest Rust toolchain
        run: |
          rustup update --no-self-update
          rustup default 1.74
          rustup target install wasm32-unknown-unknown
      - uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2.8.2
      - name: Test taplo-wasm
        working-directory: crates/taplo-wasm
        run: |
          cargo check
